name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18' # Latest LTS version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NASFAT_S }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT > $HOME/firebase-key.json
          gcloud auth activate-service-account --key-file=$HOME/firebase-key.json
          gcloud --quiet config set project nasfat-s

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token $(cat $HOME/firebase-key.json)
