name: Install Firebase Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.6.2
          cache: 'npm'  # Cache dependencies

      - name: Install Firebase tools and dependencies
        working-directory: public
        run: |
          npm install -g firebase-tools
          npm install firebase

      - name: Upload public directory
        uses: actions/upload-artifact@v3
        with:
          name: public-with-firebase
          path: public
